export {default as setCircle} from './circle/setCircle'
export {default as setHandlers} from './image/setImage'
export {default as setLine} from './line/setLine'
export {default as setRectangle} from './rectangle/setRectangle'
export {default as setText} from './text/setText'
export {default as setTriangle} from './triangle/setTriangle'
export {default as render} from './render'